In [2]:
import numpy as np

array_1 = np.array([6,10,11,1])

array_2 = np.array([5,9,10,4])

sum_array = array_1 + array_2
print(sum_array)

substract_array = array_1 - array_2
print(substract_array)

multiply_array = array_1 / array_2
print(multiply_array)

devide_array = array_1 + array_2
print(devide_array)

square_array = array_1 ** 2
print(square_array)


[11 19 21  5]
[ 1  1  1 -3]
[1.2        1.11111111 1.1        0.25      ]
[11 19 21  5]
[ 36 100 121   1]


In [12]:
import numpy as np

array_1 = np.array([25,68,4])

result_sqrt = np.sqrt(array_1)
print("square :",result_sqrt)

result_sqrt = np.sum(array_1)
print("Sum :",result_sqrt)

result_sqrt = np.average(array_1)
print("average :", result_sqrt)

result_sqrt = np.min(array_1)
print("min :",result_sqrt)

result_sqrt = np.max(array_1)
print("max :",result_sqrt)


square : [5.         8.24621125 2.        ]
Sum : 97
average : 32.333333333333336
min : 4
max : 68


In [20]:
import numpy as np

array_0 = ([[1,2,3], [4,5,6], [7,8,9]])

array_1 = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(array_0,"This is 2D Array but", type(array_1),'\n')
print(array_1,"This is 2D Array", type(array_1))



[[1, 2, 3], [4, 5, 6], [7, 8, 9]] This is 2D Array but <class 'numpy.ndarray'> 

[[1 2 3]
 [4 5 6]
 [7 8 9]] This is 2D Array <class 'numpy.ndarray'>


In [42]:
import numpy as np

array_1 = np.array([[1,2,3], [4,5,6]])

array_2 = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])

print("This is 3D Array",array_2)

print("\nArray shape in Array 1 2D:",array_1.shape)
print("Array shape Array 1 3D:",array_2.shape)

print("\nArray size in Array 1 2D:",array_1.size)
print("Array size Array 1 3D:",array_2.size)

print("\nGet Dimention in Array 1 2D:",array_1.ndim)
print("Get Dimention Array 1 3D:",array_2.ndim)

print("\nGet character Data Type in Array 1 2D:",array_1.dtype)
print("Get character Data Type in Array 1 3D:",array_2.dtype)


print("\nAccess values in Array 1 2D:",array_1[1,1])# get 5 vlue
print("Access values in Array 3D:",array_2[1,1,2])# get 12 vlue 

This is 3D Array [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Array shape in Array 1 2D: (2, 3)
Array shape Array 1 3D: (2, 2, 3)

Array size in Array 1 2D: 6
Array size Array 1 3D: 12

Get Dimention in Array 1 2D: 2
Get Dimention Array 1 3D: 3

Get character Data Type in Array 1 2D: int64
Get character Data Type in Array 1 3D: int64

Access values in Array 1 2D: 5
Access values in Array 3D: 12
